sassoftware/quickstart-sas-viya-gcp

- .gitmodules
- templates/iam.jinja
- templates/networks.jinja
- templates/sas-viya-config.yaml
- templates/sas-viya-template.jinja
- templates/sas-viya-template.jinja.schema
- templates/vms.jinja
> (GCPVIYA-1) initial topology

- SUPPORT.md
Each GitHub repository in sassoftware must now have a SUPPORT.md file indicating
that bugs and feature requests should be opened as GitHub issues.
> GCPVIYA-30 Create a SUPPORT.md file in the GitHub repository

- templates/networks.jinja
Adding the Load Balancer firewall so that the health check will be successful and users can access Viya from external machines.
> Add Load Balancer firewall

- templates/iam.py
- templates/loadbalancer.py
- templates/networks.py
- templates/sas-viya-template.jinja
- templates/sas-viya-template.jinja.schema
- templates/vms.py
This commit converts the existing jinja deployment templates to python
in order to more granularly manage the deployment.
> (GCPVIYA-33) Convert jinja templates to python

- templates/sas-viya-config.yaml
- templates/vms.py
Now that the template is in python I'm importing base64 libraries and encoding the passwords.
Also removed the need for leading '\' in the Viya version.  Hard coding this variable will be obsolete once we add in the code to read the license file.
> GCPVIYA-31 Adding base64 encoding for admin and user passwords.

- templates/sas-viya-config.yaml
Adding AdminIngressLocation and WebIngressLocation properties to the main config files.
> Adding Ingress Access properties

- templates/vms.py
Update Common code tag to commit ID hash.
> Changes for virk path update.

- templates/vms.py
> Update Waiters time out to 60 minutes and increase uri check to 5 consecutive successes.

- templates/sas-viya-config.yaml
- templates/vms.py
Changed SASU**S**erPass to SASU**s**erPass
> Fixed SASUserPass case typo

- README.md
First draft of GCP Quickstart documentation pushed to Github.
> (GCPVIYA-44) Initial documentation

- README.md
Corrected typo on gcloud command to deploy.  Changed 'cloud' to 'gcloud'
> (GCPVIYA-44) Corrected typo

- README.md
Added table of contents, user accounts section, and started the deployment monitoring section.
> (GCPVIYA-44) TOC and additional section

- templates/vms.py
This was preventing deployment into projects that were not ace-dev.
> (GCPVIYA-48)Remove hard coded project name in favor of variable.

- templates/vms.py
Redoing pull request because of merge issues.
> Create /sas/install/ansible directory for create_viya_playbook

- templates/sas-viya-template.jinja.schema
Expanded check to all valid key types: rsa1|rsa|dsa|ecdsa|ed25519
>  (GCPVIYA-58) Adding check for valid SSHPublicKey, expanded to all types

- templates/loadbalancer.py
Creating custom ssl policy with the follow cipher suites and attaching to load balancer.
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> (GCPVIYA-56) Adding Custom SSL Policy to load balancer.

- templates/sas-viya-template.jinja.schema
The case was wrong so the limits were being ignored.
> (GCPVIYA-53) updated case for min and max Length.

- templates/runtimeconfig.py
- templates/vms.py
Waiter 1 now completes just before Viya deployment.
Waiters 2-4 waits for the deployment to finish.
Waiter 5 waits for Viya servers to be ready.
Changed Waiter names to better reflect the phase of deployment.
> (GCPVIYA-51) Adding additional Waiter to accommodate slower regions.

- templates/vms.py
Latest Common Code picks up newer Viya ARK that avoids yum update to latest systemd.
> (GCPVIYA-71) Remove systemd pinning, update to latest Common Code.

- README.md
Added and optional post deployment steps section with topic on how to replace default self signed cert with your own self signed cert.
> (GCOVUTA-62) SSL Certificate replacement

- README.md
Added note about no support for SAS Data Agent at this time.
> (GCPVIYA-74) Defer Support for Data Agent

- templates/vms.py
Final update as we prep for pulling to master, removing references to develop branch.
This will be merged just before the pull request to master is submitted.
> Removing reference to develop branch

- README.md
This is the README update for hotfix release 1.1.1
> (GCPVIYA-89) Update README with required account access to deploy on GCP

- README.md
Updated README with MPP deployment option.
> (GCPVIYA-76) Doc: Update README for MPP

- README.md
Added 'Set up SAS Data Agent' section to 'Optional Post Deployment Steps' section.
> (GCPVIYA 64) Doc: Post-Deployment

- README.md
Corrections in Optional Post Deployment section.
> (GCPVIYA-64) Doc: Post-Deployment

- README.md
Update Quickstart for Viya 3.5 support.
> (GCPVIYA-103) Update Viya version

- templates/sas-viya-config.yaml
- templates/sas-viya-template.jinja.schema
> (GCPVIYA-114) Update minimum boot disk size

- README.md
- templates/iam.py
- templates/sas-viya-template.jinja.schema
- templates/vm-ansible-controller.py
Hot fix for (GCPVIYA-135) Pip Installation Error During prepare_nodes
> (GCPVIYA-136) Release 1.3.3

- templates/sas-viya-template.jinja.schema
- templates/vm-controller-mpp.py
- templates/vm-controller.py
- templates/vm-services.py
- templates/vm-worker.py
(GCPVIYA-145) Picking up new ansible version 2.10.1
> (GCPVIYA-145) Picking up new ansible version 2.10.1

- README.md
- templates/iam.py
- templates/sas-viya-template.jinja.schema
- templates/vm-ansible-controller.py
- templates/vm-controller-mpp.py
- templates/vm-controller.py
- templates/vm-services.py
- templates/vm-worker.py
Upgrading Ansible version to 2.9.14 to accommodate new minimum version required by Viya 3 deployment.
> (GCPVIYA-147) Release 1.3.4

- README.md
Adding sentence about deployment issue due to pip version.  Adding only to sassoftware repository.
> (GCPVIYA-163) Deployment issue-pip version

- README.md
Added end of support statement to GCP for Viya Quickstart.
> (MERCURY-224) - End of support
